from __future__ import annotations

from typing import Any

from .task import GenjaTaskProtocol


class PluginManager:
    def __init__(self) -> None: ...
    def load_rust_plugins_from_directory(self, path: str) -> None: ...
    def register_plugin(self, plugin: Any) -> None: ...
    def load_python_plugins_from_pyproject(self, path: str | None = None) -> None: ...
    def deregister_plugin(self, name: str) -> str | None: ...
    def plugin_names(self) -> list[str]: ...
    def plugin_names_and_groups(self) -> list[tuple[str, str]]: ...


class OptionsConfig:
    @property
    def hosts_file(self) -> str | None: ...
    @property
    def groups_file(self) -> str | None: ...
    @property
    def defaults_file(self) -> str | None: ...


class CoreConfig:
    @property
    def raise_on_error(self) -> bool: ...


class InventoryConfig:
    @property
    def plugin(self) -> str: ...
    @property
    def options(self) -> OptionsConfig: ...
    @property
    def transform_function(self) -> str | None: ...


class SSHConfig:
    @property
    def config_file(self) -> str | None: ...


class RunnerConfig:
    @property
    def plugin(self) -> str: ...
    @property
    def worker_count(self) -> int | None: ...
    @property
    def max_task_depth(self) -> int: ...
    @property
    def max_connection_attempts(self) -> int: ...


class LoggingConfig:
    @property
    def enabled(self) -> bool: ...
    @property
    def level(self) -> str: ...
    @property
    def log_file(self) -> str: ...
    @property
    def to_console(self) -> bool: ...
    @property
    def file_size(self) -> int: ...
    @property
    def max_file_count(self) -> int: ...


class Settings:
    def __init__(self) -> None: ...
    @staticmethod
    def from_file(path: str) -> Settings: ...
    @property
    def core(self) -> CoreConfig: ...
    @property
    def inventory(self) -> InventoryConfig: ...
    @property
    def ssh(self) -> SSHConfig: ...
    @property
    def runner(self) -> RunnerConfig: ...
    @property
    def logging(self) -> LoggingConfig: ...


class HostTaskResult:
    @staticmethod
    def from_python_result(result: Any) -> HostTaskResult: ...
    @property
    def status(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...


class TaskConnectionResolver: ...


class TaskDefinition:
    @staticmethod
    def from_python_class(py_task_class: type[GenjaTaskProtocol]) -> TaskDefinition: ...
    @property
    def name(self) -> str: ...
    @property
    def connection_plugin_name(self) -> str | None: ...
    @property
    def sub_tasks(self) -> list[TaskDefinition]: ...
    def to_dict(self) -> dict[str, Any]: ...
    def run_on_host(
        self,
        host: Any,
        connection_resolver: TaskConnectionResolver | None = None,
        max_depth: int = 0,
    ) -> TaskResults: ...
    def run_on_hosts(
        self,
        hosts: dict[str, Any],
        connection_resolver: TaskConnectionResolver | None = None,
        max_depth: int = 0,
    ) -> TaskResults: ...


class TaskResults:
    @property
    def task_name(self) -> str: ...
    @property
    def passed_hosts(self) -> list[str]: ...
    @property
    def failed_hosts(self) -> list[str]: ...
    @property
    def skipped_hosts(self) -> list[str]: ...
    def host_summary(self) -> dict[str, int]: ...
    def task_summary(self) -> dict[str, Any]: ...
    def merge(self, other: TaskResults) -> None: ...
    def to_dict(self, *, raw: bool = False) -> dict[str, Any]: ...
    def to_json(self, *, raw: bool = False, pretty: bool = False) -> str: ...


class Genja:
    @staticmethod
    def builder(
        hosts: dict[str, Any],
        settings: Settings | None = None,
        plugin_manager: PluginManager | None = None,
    ) -> GenjaBuilder: ...
    @staticmethod
    def from_hosts(
        hosts: dict[str, Any],
        settings: Settings | None = None,
        plugin_manager: PluginManager | None = None,
    ) -> Genja: ...
    @staticmethod
    def from_settings_file(
        path: str,
        plugin_manager: PluginManager | None = None,
    ) -> Genja: ...
    def with_runner(self, runner: str) -> Genja: ...
    def filter_by_key(self, key: str) -> Genja: ...
    def filter_by_key_value(self, key: str, value_pattern: str) -> Genja: ...
    def inventory(self) -> dict[str, dict[str, Any]]: ...
    def iter_inventory_hosts(self) -> list[tuple[str, dict[str, Any]]]: ...
    def hosts_raw(self) -> dict[str, dict[str, Any]]: ...
    def run_task(
        self,
        task_class: type[GenjaTaskProtocol],
        max_depth: int | None = None,
    ) -> TaskResults: ...


class GenjaBuilder:
    def with_plugin(self, plugin: Any) -> GenjaBuilder: ...
    def with_plugin_manager(self, plugin_manager: PluginManager) -> GenjaBuilder: ...
    def with_runner(self, runner: str) -> GenjaBuilder: ...
    def build(self) -> Genja: ...


__all__: list[str]
