from __future__ import annotations

from typing import Any

class PluginManager:
    def __init__(self) -> None: ...

    def load_rust_plugins_from_directory(self, path: str) -> None: ...
    def register_plugin(self, plugin: Any) -> None: ...
    def load_python_plugins_from_pyproject(self, path: str | None = None) -> None: ...
    def deregister_plugin(self, name: str) -> str | None: ...
    def plugin_names(self) -> list[str]: ...
    def plugin_names_and_groups(self) -> list[tuple[str, str]]: ...


__all__: list[str]
