class PluginManager:
    def __init__(self) -> None: ...

    def load_rust_plugins_from_directory(self, path: str) -> None: ...
    def deregister_plugin(self, name: str) -> str | None: ...
    def plugin_names(self) -> list[str]: ...
    def plugin_names_and_groups(self) -> list[tuple[str, str]]: ...


__all__: list[str]
