[dependencies]
async-trait = "0.1.89"

[dependencies.genja-plugin-manager]
path = "../../"

[dependencies.genja-core]
path = "../../../genja-core"

[lib]
crate-type = [
    "lib",
    "cdylib",
]
name = "plugin_connection"

[package]
edition = "2024"
name = "plugin_connection"
version = "0.1.0"
publish = false
