"""Python bindings for Genja core.

Task authoring helpers live in ``genja.task``. They are re-exported here
for compatibility, but new code should prefer:

    from genja.task import (
        IdempotencyCheckResult,
        IdempotencyMode,
        task,
        TaskMessage,
        TaskSuccessResult,
    )
"""

from .genja import (
    CoreConfig,
    Genja,
    GenjaBuilder,
    HostTaskResult,
    IdempotencyCheckResult,
    IdempotencyMode,
    InventoryConfig,
    LoggingConfig,
    OptionsConfig,
    PluginManager as _CorePluginManager,
    RunnerConfig,
    RunnerRetryConfig,
    SessionVerificationConfig,
    SSHConfig,
    Settings as _CoreSettings,
    TaskConnectionResolver,
    TaskDefinition,
    TaskRunOptions,
    TaskResults,
    Tasks,
)
from .connection import (
    ConnectionBase,
    ConnectionKey,
    ConnectionPluginBase,
    ResolvedConnectionParams,
)
from .inventory import InventoryPluginBase
from .plugin_manager import PluginManager
from .plugin import PluginBase
from .processor import (
    ProcessorPluginBase,
    TaskProcessorContext,
)
from .runner import BatchRunnerPluginBase, RunnerPluginBase
from .settings import Settings
from .task import (
    CustomTaskFactory,
    ExplicitInputSchema,
    GenjaTaskProtocol,
    Host,
    PydanticInputSchema,
    RetryConfig,
    TaskDescriptor,
    TaskExecutionMode,
    TaskFactory,
    TaskFactoryStrategy,
    TaskFailureKind,
    TaskRuntimeContext,
    TaskFailureResult,
    TaskInfo,
    TaskMessage,
    TaskMessageLevel,
    TaskRegistration,
    TaskRegistrationError,
    TaskRegistrationKey,
    TaskSkipResult,
    TaskStatus,
    TaskSuccessResult,
    create_registered_task,
    create_registered_task_by_identity,
    get_registered_task_descriptor,
    get_registered_task_descriptor_by_identity,
    list_registered_tasks,
    parse_task_identity,
    task,
    validate_task_id,
    validate_task_version,
)
from .transform import (
    TransformFunctionPluginBase,
)

assert PluginManager is _CorePluginManager
assert Settings is _CoreSettings

__all__ = [
    "HostTaskResult",
    "IdempotencyCheckResult",
    "IdempotencyMode",
    "TaskConnectionResolver",
    "TaskDefinition",
    "TaskRunOptions",
    "Tasks",
    "TaskResults",
    "Genja",
    "GenjaBuilder",
    "task",
    "ConnectionKey",
    "ResolvedConnectionParams",
    "ConnectionBase",
    "ConnectionPluginBase",
    "InventoryPluginBase",
    "PluginManager",
    "PluginBase",
    "TaskProcessorContext",
    "ProcessorPluginBase",
    "RunnerPluginBase",
    "BatchRunnerPluginBase",
    "TransformFunctionPluginBase",
    "Settings",
    "CoreConfig",
    "InventoryConfig",
    "OptionsConfig",
    "SSHConfig",
    "RunnerConfig",
    "RunnerRetryConfig",
    "SessionVerificationConfig",
    "LoggingConfig",
    "CustomTaskFactory",
    "ExplicitInputSchema",
    "GenjaTaskProtocol",
    "PydanticInputSchema",
    "RetryConfig",
    "TaskDescriptor",
    "TaskExecutionMode",
    "TaskFactory",
    "TaskFactoryStrategy",
    "TaskRegistration",
    "TaskRegistrationError",
    "TaskRegistrationKey",
    "create_registered_task",
    "create_registered_task_by_identity",
    "get_registered_task_descriptor",
    "get_registered_task_descriptor_by_identity",
    "list_registered_tasks",
    "parse_task_identity",
    "validate_task_id",
    "validate_task_version",
    "TaskInfo",
    "Host",
    "TaskRuntimeContext",
    "TaskMessage",
    "TaskMessageLevel",
    "TaskStatus",
    "TaskFailureKind",
    "TaskSuccessResult",
    "TaskFailureResult",
    "TaskSkipResult",
]
