from __future__ import annotations

from typing import Any, Awaitable

from .task import GenjaTaskProtocol

class PluginManager:
    def __init__(self) -> None: ...
    def load_rust_plugins_from_directory(self, path: str) -> None: ...
    def register_plugin(self, plugin: Any) -> None: ...
    def load_python_plugins_from_pyproject(self, path: str | None = None) -> None: ...
    def deregister_plugin(self, name: str) -> str | None: ...
    def plugin_names(self) -> list[str]: ...
    def plugin_names_and_groups(self) -> list[tuple[str, str]]: ...

class OptionsConfig:
    def __init__(
        self,
        hosts_file: str | None = None,
        groups_file: str | None = None,
        defaults_file: str | None = None,
    ) -> None: ...
    @property
    def hosts_file(self) -> str | None: ...
    @property
    def groups_file(self) -> str | None: ...
    @property
    def defaults_file(self) -> str | None: ...

class CoreConfig:
    def __init__(self, raise_on_error: bool | None = None) -> None: ...
    @property
    def raise_on_error(self) -> bool: ...

class InventoryConfig:
    def __init__(
        self,
        plugin: str | None = None,
        options: OptionsConfig | None = None,
        transform_function: str | None = None,
        transform_function_options: Any | None = None,
    ) -> None: ...
    @property
    def plugin(self) -> str: ...
    @property
    def options(self) -> OptionsConfig: ...
    @property
    def transform_function(self) -> str | None: ...
    @property
    def transform_function_options(self) -> Any | None: ...

class SSHConfig:
    def __init__(self, config_file: str | None = None) -> None: ...
    def validate(self) -> None: ...
    @property
    def config_file(self) -> str | None: ...

class RunnerConfig:
    def __init__(
        self,
        plugin: str | None = None,
        worker_count: int | None = None,
        max_task_depth: int | None = None,
        max_connection_attempts: int | None = None,
        retry: RunnerRetryConfig | None = None,
    ) -> None: ...
    @property
    def plugin(self) -> str: ...
    @property
    def worker_count(self) -> int | None: ...
    @property
    def max_task_depth(self) -> int: ...
    @property
    def max_connection_attempts(self) -> int: ...
    @property
    def retry(self) -> RunnerRetryConfig: ...

class RunnerRetryConfig:
    def __init__(
        self,
        allow: bool | None = None,
        max_attempts: int | None = None,
        delay_ms: int | None = None,
    ) -> None: ...
    @property
    def allow(self) -> bool | None: ...
    @property
    def max_attempts(self) -> int | None: ...
    @property
    def delay_ms(self) -> int | None: ...

class LoggingConfig:
    def __init__(
        self,
        enabled: bool | None = None,
        level: str | None = None,
        log_file: str | None = None,
        to_console: bool | None = None,
        file_size: int | None = None,
        max_file_count: int | None = None,
    ) -> None: ...
    @property
    def enabled(self) -> bool: ...
    @property
    def level(self) -> str: ...
    @property
    def log_file(self) -> str: ...
    @property
    def to_console(self) -> bool: ...
    @property
    def file_size(self) -> int: ...
    @property
    def max_file_count(self) -> int: ...

class Settings:
    def __init__(
        self,
        core: CoreConfig | None = None,
        inventory: InventoryConfig | None = None,
        ssh: SSHConfig | None = None,
        runner: RunnerConfig | None = None,
        logging: LoggingConfig | None = None,
    ) -> None: ...
    @staticmethod
    def from_file(path: str) -> Settings: ...
    def validate(self) -> None: ...
    @property
    def core(self) -> CoreConfig: ...
    @property
    def inventory(self) -> InventoryConfig: ...
    @property
    def ssh(self) -> SSHConfig: ...
    @property
    def runner(self) -> RunnerConfig: ...
    @property
    def logging(self) -> LoggingConfig: ...

class HostTaskResult:
    @staticmethod
    def from_python_result(result: Any) -> HostTaskResult: ...
    @property
    def status(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...

class TaskConnectionResolver: ...

class TaskDefinition:
    @staticmethod
    def from_python_class(py_task_class: type[GenjaTaskProtocol]) -> TaskDefinition: ...
    @property
    def name(self) -> str: ...
    @property
    def connection_plugin_name(self) -> str | None: ...
    @property
    def retry(self) -> dict[str, Any] | None: ...
    @property
    def sub_tasks(self) -> list[TaskDefinition]: ...
    def to_dict(self) -> dict[str, Any]: ...
    def run_on_host(
        self,
        host: Any,
        connection_resolver: TaskConnectionResolver | None = None,
        max_depth: int = 0,
    ) -> TaskResults: ...
    def run_on_hosts(
        self,
        hosts: dict[str, Any],
        connection_resolver: TaskConnectionResolver | None = None,
        max_depth: int = 0,
    ) -> TaskResults: ...

class Tasks:
    def __init__(self) -> None: ...
    def add_task(self, task_class: type[GenjaTaskProtocol]) -> None: ...
    def task_definitions(self) -> list[TaskDefinition]: ...
    def to_list(self) -> list[TaskDefinition]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> TaskDefinition: ...

class TaskResults:
    @property
    def task_name(self) -> str: ...
    @property
    def passed_hosts(self) -> list[str]: ...
    @property
    def failed_hosts(self) -> list[str]: ...
    @property
    def skipped_hosts(self) -> list[str]: ...
    def host_summary(self) -> dict[str, int]: ...
    def task_summary(self) -> dict[str, Any]: ...
    def merge(self, other: TaskResults) -> None: ...
    def to_dict(self, *, raw: bool = False) -> dict[str, Any]: ...
    def to_json(self, *, raw: bool = False, pretty: bool = False) -> str: ...

class Genja:
    @staticmethod
    def builder(
        hosts: dict[str, Any],
        settings: Settings | None = None,
        plugin_manager: PluginManager | None = None,
    ) -> GenjaBuilder: ...
    @staticmethod
    def from_hosts(
        hosts: dict[str, Any],
        settings: Settings | None = None,
        plugin_manager: PluginManager | None = None,
    ) -> Genja: ...
    @staticmethod
    def from_inventory(
        inventory: Any,
        settings: Settings | None = None,
        plugin_manager: PluginManager | None = None,
    ) -> Genja: ...
    @staticmethod
    def from_settings_file(
        path: str,
        plugin_manager: PluginManager | None = None,
    ) -> Genja: ...
    def with_runner(self, runner: str) -> Genja: ...
    def plugins_loaded(self) -> bool: ...
    def inventory_loaded(self) -> bool: ...
    def settings(self) -> Settings: ...
    def host_count(self) -> int: ...
    def host_ids(self) -> list[str]: ...
    def iter_selected_hosts(self) -> list[tuple[str, dict[str, Any]]]: ...
    def filter_by_key(self, key: str) -> Genja: ...
    def filter_by_key_value(self, key: str, value_pattern: str) -> Genja: ...
    def inventory(self) -> dict[str, dict[str, Any]]: ...
    def inventory_full(self) -> dict[str, Any]: ...
    def inventory_raw(self) -> dict[str, Any]: ...
    def iter_inventory_hosts(self) -> list[tuple[str, dict[str, Any]]]: ...
    def hosts_raw(self) -> dict[str, dict[str, Any]]: ...
    def run_task(
        self,
        task_class: type[GenjaTaskProtocol],
        max_depth: int | None = None,
    ) -> TaskResults: ...
    def run_task_async(
        self,
        task_class: type[GenjaTaskProtocol],
        max_depth: int | None = None,
    ) -> Awaitable[TaskResults]: ...
    def run_tasks(
        self,
        tasks: Tasks,
        max_depth: int | None = None,
    ) -> list[TaskResults]: ...
    def run_tasks_async(
        self,
        tasks: Tasks,
        max_depth: int | None = None,
    ) -> Awaitable[list[TaskResults]]: ...

class GenjaBuilder:
    def with_plugin(self, plugin: Any) -> GenjaBuilder: ...
    def with_plugin_manager(self, plugin_manager: PluginManager) -> GenjaBuilder: ...
    def with_runner(self, runner: str) -> GenjaBuilder: ...
    def build(self) -> Genja: ...

__all__: list[str]
