from __future__ import annotations

from typing import Any

class OptionsConfig:
    def __init__(
        self,
        hosts_file: str | None = None,
        groups_file: str | None = None,
        defaults_file: str | None = None,
    ) -> None: ...
    @property
    def hosts_file(self) -> str | None: ...
    @property
    def groups_file(self) -> str | None: ...
    @property
    def defaults_file(self) -> str | None: ...

class CoreConfig:
    def __init__(self, raise_on_error: bool | None = None) -> None: ...
    @property
    def raise_on_error(self) -> bool: ...

class InventoryConfig:
    def __init__(
        self,
        plugin: str | None = None,
        options: OptionsConfig | None = None,
        transform_function: str | None = None,
        transform_function_options: Any | None = None,
    ) -> None: ...
    @property
    def plugin(self) -> str: ...
    @property
    def options(self) -> OptionsConfig: ...
    @property
    def transform_function(self) -> str | None: ...
    @property
    def transform_function_options(self) -> Any | None: ...

class SSHConfig:
    def __init__(self, config_file: str | None = None) -> None: ...
    def validate(self) -> None: ...
    @property
    def config_file(self) -> str | None: ...

class RunnerConfig:
    def __init__(
        self,
        plugin: str | None = None,
        worker_count: int | None = None,
        max_task_depth: int | None = None,
        max_connection_attempts: int | None = None,
        retry: RunnerRetryConfig | None = None,
    ) -> None: ...
    @property
    def plugin(self) -> str: ...
    @property
    def worker_count(self) -> int | None: ...
    @property
    def max_task_depth(self) -> int: ...
    @property
    def max_connection_attempts(self) -> int: ...
    @property
    def retry(self) -> RunnerRetryConfig: ...

class RunnerRetryConfig:
    def __init__(
        self,
        allow: bool | None = None,
        max_attempts: int | None = None,
        delay_ms: int | None = None,
    ) -> None: ...
    @property
    def allow(self) -> bool | None: ...
    @property
    def max_attempts(self) -> int | None: ...
    @property
    def delay_ms(self) -> int | None: ...

class LoggingConfig:
    def __init__(
        self,
        enabled: bool | None = None,
        level: str | None = None,
        log_file: str | None = None,
        to_console: bool | None = None,
        file_size: int | None = None,
        max_file_count: int | None = None,
    ) -> None: ...
    @property
    def enabled(self) -> bool: ...
    @property
    def level(self) -> str: ...
    @property
    def log_file(self) -> str: ...
    @property
    def to_console(self) -> bool: ...
    @property
    def file_size(self) -> int: ...
    @property
    def max_file_count(self) -> int: ...

class Settings:
    def __init__(
        self,
        core: CoreConfig | None = None,
        inventory: InventoryConfig | None = None,
        ssh: SSHConfig | None = None,
        runner: RunnerConfig | None = None,
        logging: LoggingConfig | None = None,
    ) -> None: ...
    @staticmethod
    def from_file(path: str) -> Settings: ...
    def validate(self) -> None: ...
    @property
    def core(self) -> CoreConfig: ...
    @property
    def inventory(self) -> InventoryConfig: ...
    @property
    def ssh(self) -> SSHConfig: ...
    @property
    def runner(self) -> RunnerConfig: ...
    @property
    def logging(self) -> LoggingConfig: ...

__all__: list[str]
